### ISSUE TITLE
Help with the install

### ISSUE THREAD

**Issue by paulitas** [hsk-dk/home-assistant-thermex#2]
Hey i am new to homeassistant and want to know how to make this work.
Maybe a video guide or some more guide will be very nice. Thanks

**Comment by hsk-dk** [comment]
Readme updated, if more help is needed please seek help in https://community.home-assistant.io/

**Comment by hsk-dk** [comment]
Readme have been updated with more details. Only the Thermex app is needed to enable the api.

**Comment by paulitas** [comment]
I downloaded latest version thermex app version from Google shop and its not the same like in your guide and its not connecting to the Google acount crashing and starting over again 
![Screenshot_20241106-191003](https://github.com/user-attachments/assets/5273cbab-68f1-45c2-8b4b-70d77120777b)
![Screenshot_20241106-190957](https://github.com/user-attachments/assets/a0089bce-1211-49bf-b96f-a3bcec9be9fa)

**Comment by paulitas** [comment]
Ok I think that will cost to much thank you very much for your time
