### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by PalleLC** [hsk-dk/home-assistant-thermex#3]
I tried to install and get following log errors 
![THERMEX FAIL](https://github.com/user-attachments/assets/95c2ca49-5327-44b9-a7fc-732ad832ebc1)

I have updated the configuration yaml and restarted HA. 

thermex_api:
host: 192.168.1.7
password: 12345678

**Comment by hsk-dk** [comment]
Please try to update your configuration to:
thermex_api:
host: "192.168.1.7"
password: "12345678"

**Comment by PalleLC** [comment]
Thanks.. It works.. :-) 
Really great.. Play time..
