### ISSUE TITLE
Various problems.

### ISSUE THREAD

**Issue by BatmanKuhn** [hsk-dk/home-assistant-thermex#4]
I get authentication failure.
App version is IOS (v1.32/1.11) SmartHome enabled with password. (same as using in configuration.yaml)
__
Logger: custom_components.thermex_api.api
Kilde: custom_components/thermex_api/api.py:32
__

**Comment by hsk-dk** [comment]
Are both the ip and password enclosed ' ' in configuration.yaml?

**Comment by BatmanKuhn** [comment]
encosed in "

**Comment by BatmanKuhn** [comment]
Detected that custom integration 'thermex_api' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2025.5, it should be updated to import functions used from discovery directly at custom_components/thermex_api/__init__.py, line 59: hass.helpers.discovery.load_platform('sensor', DOMAIN, {}, config), please report it to the author of the 'thermex_api' custom integration

**Comment by BatmanKuhn** [comment]
Yes I can try - I edited it, as I was not sure if i did a misspelling. 
Also "rebooted" the hood. 
Will try something "simple" as password.

**Comment by BatmanKuhn** [comment]
I changed the password to one word phrase - now I get **two new entities:**
light.thermex_light (which I can turn on / off) - Yeehah
sensor.thermex_fan_sensor - which I cannot turn on/ff 

Am I missing something?

**Comment by hsk-dk** [comment]
sensor.thermex_fan_sensor only shows the status of the hood. 
the hood can be turned on and off using the switch (which should have been added also) switch.thermex_fan_switch

for more control 2 new actions should also have been added (Check Developer tools -> actions)
Thermex (api): update_fan
Thermex (api): update_light
Choose YAML mode for help.

**Comment by BatmanKuhn** [comment]
Thanks - almost there. I just never used services like that.
Should this not work?

tap_action:
  action: call-service
  service: thermex_api.update_fan
  data:
    fanonoff: 0
    fanspeed: 3
